vscode:
  extensions:
    - PKief.material-icon-theme@3.9.1:g1O+jL+iaYZp5mMmzpPEug==
    - rocketseat.RocketseatReactJS@2.2.0:CMZI2JF+9mcg15CoJkRPOQ==
    - rocketseat.RocketseatReactNative@2.2.0:R1GKe6htx17bP/HX+6BUFQ==
    - bceskavich.theme-dracula-at-night@2.5.0:v0q2qqzz3Gq1Aphw8iH/lw==